In [2]:
import numpy as np

In [7]:
a=np.array([20,21,23,25,23,26,25])
a

array([20, 21, 23, 25, 23, 26, 25])

In [8]:
a.ndim # parameter

1

In [9]:
a.shape

(7,)

In [11]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b.ndim

2

In [14]:
b.shape

(2, 3)

In [15]:
b=np.array([[1,2,3],[4,5,6],[10,20,30]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [16]:
b.ndim

2

In [17]:
b.shape

(3, 3)

In [18]:
l=[10,20,30]
l

[10, 20, 30]

In [19]:
np.array(l)

array([10, 20, 30])

In [20]:
matrix=[[10,20,30],[40,50,60],[100,200,300]]
matrix

[[10, 20, 30], [40, 50, 60], [100, 200, 300]]

In [21]:
np.array(matrix)

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [100, 200, 300]])

In [24]:
a=np.arange(1,100,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [26]:
b=np.linspace(0,5,10)
b

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [28]:
a=np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [30]:
c=np.ones((4,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
e=np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
e=np.eye(3,2)
e

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [33]:
a=np.diag([7,9,3,4])
a

array([[7, 0, 0, 0],
       [0, 9, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [34]:
c=np.random.rand(5)
c

array([0.86842264, 0.39632324, 0.13478936, 0.75679376, 0.14165264])

In [36]:
c=np.random.randn(5)
c

array([ 0.34342778, -0.38333003, -0.0820134 , -0.18383731, -0.05806826])

In [37]:
a=np.array([[23,2,6],[4,11,56]])
a

array([[23,  2,  6],
       [ 4, 11, 56]])

In [38]:
x=np.sort(a,axis=1)
x

array([[ 2,  6, 23],
       [ 4, 11, 56]])

In [40]:
x=np.sort(a,axis=0)
x

array([[ 4,  2,  6],
       [23, 11, 56]])

In [41]:
a=np.arange(25)
print(a)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)


In [42]:
a=np.array([[10,20,30],[40,50,60]])
print("Shape:{}".format(a.shape))
print(a)

Shape:(2, 3)
[[10 20 30]
 [40 50 60]]


In [43]:
c=a.T
print(c)

[[10 40]
 [20 50]
 [30 60]]


In [44]:
a=np.random.randint(0,20,5)
a

array([ 5, 14,  8,  6,  4])

In [45]:
a[[2,4,3]]


array([8, 4, 6])

In [46]:
a[[2]]=100
a

array([  5,  14, 100,   6,   4])

In [47]:
a=np.diag([1,2,3,4])
a*a

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [48]:
a=np.array([[1,2,1],[3,4,3],[5,6,5]])
b=np.array([[4,4,1],[4,4,2],[4,4,3]])
print(np.matmul(a,b))

[[16 16  8]
 [40 40 20]
 [64 64 32]]


In [49]:
a=np.array([1,1,0,1],dtype=bool)
b=np.array([1,0,1,0],dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True,  True])

In [50]:
a=np.array([1,1,0,1])
b=np.array([1,0,1,0])
np.logical_or(a,b)

array([ True,  True,  True,  True])

In [51]:
a+b

array([2, 1, 1, 1])

In [52]:
a=np.array([[1,2],[3,4]])
a.sum()

10

In [3]:
a=np.array([1,2,3,4])
b=np.array([5,1,20,0])
a==b

array([False, False, False, False])

In [4]:
a<b

array([ True, False,  True, False])

In [5]:
a>b

array([False,  True, False,  True])

In [6]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [7]:
np.log(a)

C:\Users\ritik\AppData\Local\Temp\ipykernel_23832\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [8]:
a=np.arange(0,10,1)
print(format(a))

[0 1 2 3 4 5 6 7 8 9]


In [21]:
a.argmin()

0

In [22]:
a.argmax()

2

In [9]:
np.min(a)

0

In [10]:
np.max(a)

9

In [12]:
np.mean(a)

4.5

In [11]:
np.sum(a)

45

In [13]:
np.median(a)

4.5

In [14]:
np.std(a)

2.8722813232690143

In [15]:
x=np.array([1,20,2,30])
np.sum(x)

53

In [17]:
a=np.array([[1,10],[20,2]])
a

array([[ 1, 10],
       [20,  2]])

In [18]:
a.sum(axis=0)

array([21, 12])

In [20]:
a.sum(axis=1)

array([11, 22])